name: CI-sorted-strings

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  # Run tests for any PRs.
  pull_request:

jobs:
  sorting:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build dependencies
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: sisl-check
          cache-from: type=local,src=/tmp/.docker-cache
          cache-to: type=local,dest=/tmp/.docker-cache
          load: true
          target: sisl-check

      - name: Run string sorting check
        run: |
          set -ex
          export TEST_CMD="main.py sislstrings.bib";
          docker run -i --rm sisl-check /bin/python "$TEST_CMD";
